# hash-identificacao: 11d65592e16f0c97b9664810e27f19f94e3c24f2a86abf64c883168c6cfc805c

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# Formata o JSON das respostas com indentação
spring.jackson.serialization.INDENT_OUTPUT=true
