# hash-identificacao: 7ee5f4fc6e703f0077a2a15f90c775823337a05639a75b65e99a21763b4895fe

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dados-pessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true

# Formata o JSON das respostas com indentação
spring.jackson.serialization.INDENT_OUTPUT=true